### Importing libraries:

In [8]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np


### Importing the trained model:

In [9]:
from keras.preprocessing import image
model = load_model('trained_model.h5')

In [10]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

### Forming rectangle aroung face:

In [11]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

### Web cam:

In [12]:
# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Hari'
        elif(pred[0][1]>0.5):
            name='Renga'
        elif(pred[0][2]>0.5):
            name='Uma'
        elif(pred[0][3]>0.5):
            name='Viji'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[1.0000000e+00 1.5984377e-26 2.1082458e-17 8.1333174e-10]]
[[1.0000000e+00 1.2796025e-34 0.0000000e+00 1.1280821e-09]]
[[6.6865522e-07 2.5169634e-11 7.5129174e-11 9.9999928e-01]]
[[1.0000000e+00 0.0000000e+00 0.0000000e+00 1.1700795e-27]]
[[1.0000000e+00 2.0824014e-35 1.4425968e-20 1.3621392e-13]]
[[1.0000000e+00 1.6090446e-35 4.5775302e-31 1.4642168e-16]]
[[1.0000000e+00 0.0000000e+00 0.0000000e+00 6.7461837e-31]]
[[1.000000e+00 0.000000e+00 0.000000e+00 3.585501e-36]]
[[1.0000000e+00 0.0000000e+00 0.0000000e+00 2.7172749e-31]]
[[1.000000e+00 0.000000e+00 0.000000e+00 4.683709e-30]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 0.0000000e